### ISSUE TITLE
[Quetion] How to load balance control plane in ARP mode (k3s)

### ISSUE THREAD

**Issue by changsheng1239** [kube-vip/kube-vip#230]
Successfully deployed kube-vip as daemonset in ARP mode. But how do I load balance the traffic to my control planes? Right now all the traffic will only go through the control plane leader holding the VIP. Not sure whether I am 100% right tho, any answer would be gladly appreciated! 😄 

And btw, thanks for this amazing tools. Goodbye to haproxy + keepalived!

**Comment by thebsdbox** [comment]
Hello!

So this is part of the roadmap [here](https://github.com/kube-vip/kube-vip/blob/main/ROADMAP.md#ha-kubernetes-control-plane)

Load-Balancing the control-plane was kinda removed from the docs last year due to a conflict of interest issue (no longer an issue). It's going to be reimplemented in the near future (probably with IPVS)
