### ISSUE TITLE
Leader election callbacks swallow errors that should probably be fatal

### ISSUE THREAD

**Issue by detiber** [kube-vip/kube-vip#276]
**Describe the bug**

When configured for ARP and/or Equinix Metal support leader election callbacks, particularly `OnStartedLeading` are swallowing errors that should likely be fatal.

For example, any errors raised by [`packet.AttachEIP()`](https://github.com/kube-vip/kube-vip/blob/c333e2a1eb8772ccf9b22198333f70151e4012db/pkg/packet/eip.go#L13) do not cause failure. This results in kube-vip continuing to run as if there are no errors, without the EIP being assigned to the host.

As an aside, there is also potential for an unhandled error if detaching an IP assignment fails: https://github.com/kube-vip/kube-vip/blob/c333e2a1eb8772ccf9b22198333f70151e4012db/pkg/packet/eip.go#L43

**To Reproduce**

I haven't yet been able to reproduce this deterministically yet, but it happens relatively frequently in automated testing for CAPP. 

**Expected behavior**

Any potentially fatal errors in `OnStartedLeading` callbacks should result in a panic.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 1804
 - Kubernetes Version: v.1.22.0
 - Kube-vip Version: v0.3.8

**`Kube-vip.yaml`:**

generated with:
```sh
ctr images pull ghcr.io/kube-vip/kube-vip:v0.3.8 && ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.3.8 vip /kube-vip manifest pod --interface bond0 --address {{ .controlPlaneEndpoint }} --controlplane --arp --leaderElection --metal --metalKey {{ .apiKey }} --metalProjectID ${PROJECT_ID} > /etc/kubernetes/manifests/kube-vip.yaml
```

**Comment by thebsdbox** [comment]
Good spot. I'll try and investigate from next week.

**Comment by ezeriver94** [comment]
Hi, I'm having a similar issue as the one described in this bug, but my problem is when running the following code after acquiring the lease:
```
err = cluster.Network.AddIP()
if err != nil {
	log.Warnf("%v", err)
}
```

I can see the following logs:
```
time="2023-03-20T08:18:53Z" level=info msg="Node [{{NODE}}] is assuming leadership of the cluster"
time="2023-03-20T08:18:53Z" level=warning msg="could not add ip: no such device"
time="2023-03-20T08:18:53Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [{{IP}}]"
time="2023-03-20T08:18:53Z" level=warning msg="Re-applying the VIP configuration [{{IP}}] to the interface [{{INTERFACE}}]"
time="2023-03-20T08:18:53Z" level=warning msg="could not add ip: no such device"
time="2023-03-20T08:18:56Z" level=warning msg="Re-applying the VIP configuration [{{IP}}] to the interface [{{INTERFACE}}]"
time="2023-03-20T08:18:56Z" level=warning msg="could not add ip: no such device"
```

I can manually run `ip addr replace ...` and it works, and restarting the container makes it work again, but without restarting the error is printed every time, breaking the access to the cluster (as the lease gets locked up by the current instance). I think this should also be a Fatal error instead of only a Warning

**Comment by thebsdbox** [comment]
What is the interface? (Type etc)

**Comment by ezeriver94** [comment]
Sorry, this is the file: 

https://github.com/kube-vip/kube-vip/blob/8af0391bc910ddd327a69c69632a411a96c5f807/pkg/cluster/service.go#L49-L52

In my case, the default device is getting recreated on all nodes; when that happens, the leader instance of kube-vip gets correctly restarted, but the other ones does not. If during the restart, the leader loses the Lease and some other instance acquires it, when it starts reconciling it faces the "no such device error" when trying to add the IP with netlink. As this error is not fatal, the container tries again forever, failing each time (I think there is something cached pointing to the old definition of the interface, which got recreated). Putting a Fatal log there instead of a warning makes the container crash and restart, fixing the issue.

**Comment by ezeriver94** [comment]
Hi @thebsdbox were you able to check this issue? IMO leader election should be lost in case of recreating the default device and that should probably fix this problem

**Comment by zakthan** [comment]
Exactly the same problem that @ezeriver94 described happened to me today.
Container kept running but could not assign IP:
```
 E1002 16:58:04.774677       1 leaderelection.go:330] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system
/leases/plndr-cp-lock": dial tcp 127.0.0.1:6443: connect: connection refused
I1002 17:02:25.197726       1 leaderelection.go:258] successfully acquired lease kube-system/plndr-cp-lock
time="2023-10-02T17:02:25Z" level=info msg="Node [*****] is assuming leadership of the cluster"
time="2023-10-02T17:02:25Z" level=warning msg="could not add ip: no such device"
time="2023-10-02T17:02:25Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [10.***.***.***]"
time="2023-10-02T17:02:25Z" level=warning msg="Re-applying the VIP configuration [10.***.***.***] to the interface [bond0.****]"
time="2023-10-02T17:02:25Z" level=warning msg="could not add ip: no such device"

```
Also containers from other nodes did not try to get the lead
Solution @ezeriver94 proposing should fix the issue plus this event should be of higher level than warning.

**Comment by thebsdbox** [comment]
Makes sense, I'll change the behaviour here.

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/kube-vip/pull/623

**Comment by thebsdbox** [comment]
These issues have largely been addressed.

**Comment by zakthan** [comment]
Hi @thebsdbox ,
Unfortunately behavior has changed again at the latest tags. Probably some code refactoring has happened.
For example for **v0.9.2** we get this message: `ERROR could not add ip: no such device` but pod never restarts to self heal so VIP become unresponsive (in my case it was because the index of the VIP interface changed after netplan apply)
I think the new code is [here ](https://github.com/kube-vip/kube-vip/blob/main/pkg/vip/address.go#L327)

**Comment by oivindoh** [comment]
Are there several data paths for this? In 1.0.1 I'm seeing this in a cluster

2025/11/04 16:29:10 WARN could not add ip: no such device
2025/11/04 16:29:13 WARN could not add ip: no such device
2025/11/04 16:29:16 WARN could not add ip: no such device
2025/11/04 16:29:19 WARN could not add ip: no such device
