### ISSUE TITLE
Support DHCP static leases.

### ISSUE THREAD

**Issue by reitermarkus** [kube-vip/kube-vip#354]
**Is your feature request related to a problem? Please describe.**

Currently, when deploying a service with `loadBalancerIP: 0.0.0.0`, it gets a random MAC address. I'd like to assign static DHCP leases in my router for some services, either based on a specific MAC address or preferably a client identifier.

I saw that in https://github.com/kube-vip/kube-vip/pull/229 a `kube-vip.io/hwaddr` annotation was added. I'm not sure if this is supposed to work as I expected it to: I added a `kube-vip.io/hwaddr: b6:82:16:b2:86:b2` to one of my services and a static lease with this MAC address to my router. It seems like `kube-vip` then actually tries to use this MAC address, however the service IP stays `<pending>` and the logs show:

```
Could not bring up interface [vip-bf85e6f5] : address already in use
```

**Describe the solution you'd like**

Allow specifying a fixed MAC address or client identifier using an annotation which will be used to get the DHCP static lease.

**Describe alternatives you've considered**

- Using a static IP for the service, but in that case the IP needs to be managed both in the service definition and the router.
- Maybe UPNP would work for my use case, however as far as I understand it, `enableUPNP` will currently enable it globally. I would only want to enable it for some services, not all.

**Additional context**

N/A

**Comment by valtzu** [comment]
I agree it's a bit counter-intuitive – the dhcp feature is not that useful unless you also use dynamic dns.

I did some debugging and noticed that the issue is that it's not even sending `DHCPDISCOVER` if mac address is manually defined:

![image](https://user-images.githubusercontent.com/652734/183305173-7058a3c9-4359-499a-a27b-fa10b9575964.png)

_(no idea from where the 0.1.3.0 IP comes from – didn't find it in source code)_

---

I created a [pull request](https://github.com/kube-vip/kube-vip/pull/434) that fixes this issue but not 100% sure if it breaks something else.
