### ISSUE TITLE
IPVS based Service LoadBalancer?

### ISSUE THREAD

**Issue by rgl** [kube-vip/kube-vip#496]
Is it possible to create an IPVS based Service LoadBalancer?

It seems that only the Control Plane VIP can use IPVS.

But maybe I'm missing something in the following configuration?

```bash
(
  wget -qO- "$kube_vip_rbac_url"
  echo ---
  ctr run --rm --net-host "$kube_vip_image" vip \
    /kube-vip \
    manifest \
    daemonset \
    --arp \
    --interface eth1 \
    --address "$vip" \
    --inCluster \
    --taint \
    --controlplane \
    --enableLoadBalancer \
    --leaderElection \
    --services
  echo ---
  wget -qO- "$kube_vip_cloud_provider_url"
  echo ---
  kubectl create configmap \
    -n kube-system \
    kubevip \
    --output yaml \
    --dry-run \
    --from-literal "range-global=$lb_ip_range"
) | kubectl apply -f -
```

**Comment by kriansa** [comment]
How would that differ from having `kube-proxy` running in IPVS mode and the service `externalTrafficPolicy` as `Cluster`?

**Comment by rgl** [comment]
Not sure I understood. Kube-proxy isn't only used for internal cluster communications? If so, to be able to reach the cluster from the outside we need to use a LoadBalancer object, which is not handled by Kube-proxy. Hence the need for this to be handled by kube-vip?

**Comment by kriansa** [comment]
I might be wrong too, so take it with a grain of salt.

When you create a service on k8s, by default it will set the flag `externalTrafficPolicy` to `Cluster`, and this means that every node in your cluster will be able to receive a request and forward it to the node that actually contain a pod of your service. That is done by `kube-proxy`, which either creates `iptables` rules OR `IPVS` entries that are responsible to forward the traffic using NAT. IPVS is a superior choice because not only do you get more performance, but you can use different scheduling methods, whereas on `iptables` you're limited to round-robin.

Differently though, control-plane runs [kube-api-server](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) which is the API that your whole cluster connects to. This API server, regardless of how many control-planes you have, only responds to requests directly sent to them, and none of them are proxied nor distributed across your control-planes, because they don't run `kube-proxy`.

Solutions like a VIP for the control-plane makes a ton of sense for high availability, since in case one server is down, that same IP address gets allocated to another. However, there's no load-balancing involved at all. That's why enabling IPVS along VIP makes a ton of sense for control-plane, as k8s doesn't provide a built-in load balancer, and IPVS is able to send requests across your control-planes - so in this context, kube-vip + IPVS is working like `kube-proxy`.

For your service type `LoadBalancer` though, a separate IPVS service isn't that useful, as that is already being provided by `kube-proxy` when the service `externalTrafficPolicy` is `Cluster` (the default). Announcing a VIP is enough to get both HA and LB.

Now answering your question more directly. By default, `kube-proxy` will use iptables, but you can easily configure it to use IPVS instead (there are many articles online, but check [official docs too](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/)).

**Comment by thebsdbox** [comment]
At the moment, kube-vip is only focussed on the control plane of the network (i.e. creating an address on the network or configuring routers) in order to get traffic to the Kubernetes cluster. Once the traffic hits the chosen node, then `kube-proxy`will load balance it to one of the underlying pods (using either iptables or IPVS).
